baseURL = "https://prasad-firame.github.io/"
languageCode = "en-us"
title = ""
theme = "PaperMod"

[params]
  env = "production"
  description = "Building, breaking, and debugging the future"
  author = "Prasad Firame"
  
  # Dark mode by default
  defaultTheme = "dark"
  disableThemeToggle = false
  
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowReadingTime = true
  ShowShareButtons = false
  ShowWordCount = true
  
  # Hacker aesthetic
 [params.homeInfoParams]
  Content = """
  """


# Navigation with hacker vibes
[[menu.main]]
  name = "~/posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  name = "~/tags"
  url = "/tags/"
  weight = 20



[[menu.main]]
  name = "~/about"
  url = "/about/"
  weight = 30

[[menu.main]]
  name = "~/experience"
  url = "/experience/"
  weight = 25

# Social links
[[params.socialIcons]]
  name = "github"
  url = "https://github.com/neooxdev"

[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/acexdev"

[[params.socialIcons]]
  name = "email"
  url = "prasadfirame18@email.com"

# Better code display
[params.assets]
  disableFingerprinting = false
  customCSS = ["css/custom.css"]


[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = true
  lineNos = false
  noClasses = false
  style = "monokai"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
